{"name": "Заказы пользователя из раздела «История заказов» отображаются на странице «Лента заказов»", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message:", "trace": "self = <tests.test_order_feed_page.TestOrderFeedPage object at 0x00000210CEC28A90>\ndriver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"650046930a45c2620b28f274683011c0\")>\n\n    @allure.title('Заказы пользователя из раздела «История заказов» отображаются на странице «Лента заказов»')\n    def test_order_user_history_and_order_feed(self, driver):\n>       num_order = OrderFeedPage(driver).base_check_order_user_history_and_order_feed()\n\ntests\\test_order_feed_page.py:13: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages\\order_feed_page.py:195: in base_check_order_user_history_and_order_feed\n    number_order = self.base_check_number_new_order()\npages\\order_feed_page.py:184: in base_check_number_new_order\n    self.wait__element_number_orders()\npages\\order_feed_page.py:52: in wait__element_number_orders\n    return self.wait_element_(locator, text_value)\npages\\base_page.py:43: in wait_element_\n    return WebDriverWait(self.driver, 15).until(expected_conditions.none_of(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"650046930a45c2620b28f274683011c0\")>, method = <function none_of.<locals>.none_of_condition at 0x00000210CED48CA0>\nmessage = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message:\n\nvenv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py:105: TimeoutException"}, "steps": [{"name": "Общие шаги: заказы пользователя из раздела \"История заказов\" отображаются на странице \"Лента заказов\"", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\pages\\order_feed_page.py\", line 195, in base_check_order_user_history_and_order_feed\n    number_order = self.base_check_number_new_order()\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\pages\\order_feed_page.py\", line 184, in base_check_number_new_order\n    self.wait__element_number_orders()\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\pages\\order_feed_page.py\", line 52, in wait__element_number_orders\n    return self.wait_element_(locator, text_value)\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\pages\\base_page.py\", line 43, in wait_element_\n    return WebDriverWait(self.driver, 15).until(expected_conditions.none_of(\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Общие шаги получения номера нового заказа", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\pages\\order_feed_page.py\", line 184, in base_check_number_new_order\n    self.wait__element_number_orders()\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\pages\\order_feed_page.py\", line 52, in wait__element_number_orders\n    return self.wait_element_(locator, text_value)\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\pages\\base_page.py\", line 43, in wait_element_\n    return WebDriverWait(self.driver, 15).until(expected_conditions.none_of(\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Общие шаги для авторизации", "status": "passed", "steps": [{"name": "Ожидаем кликабельность кнопки \"Личный кабинет\"", "status": "passed", "start": 1704913958043, "stop": 1704913958069}, {"name": "Нажимаем на кнопку \"Войти в аккаунт\" на главной странице", "status": "passed", "start": 1704913958069, "stop": 1704913958129}, {"name": "Нажимаем на поле \"Email\" на странице авторизации", "status": "passed", "start": 1704913958135, "stop": 1704913958186}, {"name": "Вводим email зарегистрированного пользователя на странице авторизации", "status": "passed", "start": 1704913958186, "stop": 1704913958248}, {"name": "Нажимаем на поле \"Пароль\" на странице авторизации", "status": "passed", "start": 1704913958248, "stop": 1704913958293}, {"name": "Вводим пароль зарегистрированного пользователя на странице авторизации", "status": "passed", "start": 1704913958293, "stop": 1704913958334}, {"name": "Ожидаем кнопку \"Войти\" на странице авторизации", "status": "passed", "start": 1704913958334, "stop": 1704913958352}, {"name": "Нажимаем на кнопку \"Войти\" на странице авторизации", "status": "passed", "start": 1704913958352, "stop": 1704913958400}], "start": 1704913956386, "stop": 1704913958403}, {"name": "Перетаскиваем ингредиент в заказ", "status": "passed", "start": 1704913958403, "stop": 1704913959522}, {"name": "Нажимаем на кнопку \"Оформить заказ\"", "status": "passed", "start": 1704913959522, "stop": 1704913959572}, {"name": "Ожидание появления нового номера заказов", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\allure_commons\\_allure.py\", line 192, in impl\n    return func(*a, **kw)\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\pages\\order_feed_page.py\", line 52, in wait__element_number_orders\n    return self.wait_element_(locator, text_value)\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\pages\\base_page.py\", line 43, in wait_element_\n    return WebDriverWait(self.driver, 15).until(expected_conditions.none_of(\n  File \"C:\\Users\\123\\PycharmProjects\\Diplom\\Diplom_3\\venv\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 105, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1704913959574, "stop": 1704913975088}], "start": 1704913956386, "stop": 1704913975119}], "start": 1704913956386, "stop": 1704913975119}], "start": 1704913956386, "stop": 1704913975120, "uuid": "f6c85ed9-b5f8-407e-80c3-db8f4087b45a", "historyId": "07b1a82eda63055fd8a5648116a3fd46", "testCaseId": "07b1a82eda63055fd8a5648116a3fd46", "fullName": "tests.test_order_feed_page.TestOrderFeedPage#test_order_user_history_and_order_feed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_order_feed_page"}, {"name": "subSuite", "value": "TestOrderFeedPage"}, {"name": "host", "value": "LAPTOP-588797DN"}, {"name": "thread", "value": "38780-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_order_feed_page"}]}